### ISSUE TITLE
0.4.0 endless parsing

### ISSUE THREAD

**Issue by Xymanek** [EliotVU/UnrealScript-Language-Service#12]
I've tried 0.4.0 and I've been met with endless parsing.

Mod: https://github.com/WOTCStrategyOverhaul/X2WOTCCommunityHighlander/tree/development
I've also added SrcOrig as per your recommendation as "Add folder to workspace"

Output: https://gist.github.com/Xymanek/cb912eb539f3d13c49fd9a3ae7c7b05d Note the following:
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7EBA076CF 
 2: 00007FF7EA69CA46 
 3: 00007FF7EA69CC56 
 4: 00007FF7E9883828 
 5: 00007FF7E98837C9 
 6: 00007FF7E98FC110 
 7: 00007FF7E98FAF14 
 8: 00007FF7E98F8AC9 
 9: 00007FF7E99043FB 
10: 00007FF7E99044A9 
11: 00007FF7E951DC4D 
12: 00007FF7E96CFC69 
13: 00007FF7E9AEFDF2 
[Info  - 11:00:03 AM] Connection to server got closed. Server will restart.
```
This happens in an endless loop. At the point when this happens at least 4-5 GB of RAM is free

**Comment by EliotVU** [comment]
Ah thanks for reporting this, I had run into this issue during the development of 0.4.0, but as I re-factored the indexing, the issue had vanished, guess I was wrong :(

Nonetheless, I've already found a solution to this problem and will publish it hopefully soon!

Btw, do you have "Index all Documents" enabled? If so disable it and try again, should reduce the overall memory print.

**Comment by Xymanek** [comment]
Just tried with 0.4.2, same issue. Here are my settings:

![image](https://user-images.githubusercontent.com/2865341/66517626-1fe82600-eaec-11e9-9550-988bb00cf03e.png)

**Comment by Xymanek** [comment]
Bump

**Comment by EliotVU** [comment]
I have been trying to figure why this isn't working, no success thus far :(

The solution I had applied is apparently non-effective for non-debug builds.

**Comment by Xymanek** [comment]
I've tried 0.4.3 and it seems like the issue is fixed. Nice! Even the "Index all" option is working fine.

There are actual parsing errors however, remaining, but I'll post them in separate issues
