### ISSUE TITLE
'intrinsic' is not recognized as a field modifier

### ISSUE THREAD

**Issue by PolaricEntropy** [EliotVU/UnrealScript-Language-Service#125]
The 'intrinsic' keyword is not recognized as a field modifier. It works fine to use 'intrinsic' instead of 'native' for classes though.

https://puu.sh/GINmQ/2b417829ba.png

**Comment by midnight-dev** [comment]
Weird. It can be found in several places already, like [UnrealScript syntax YAML, L183](https://github.com/EliotVU/UnrealScript-Language-Service/blob/master/syntaxes/UnrealScript.YAML-tmLanguage#L183) and [UC Lexer L124](https://github.com/EliotVU/UnrealScript-Language-Service/blob/master/grammars/UCLexer.g4#L124). 

Much of my recent shenanigans with UScript just involve mutators for UT2004, so intrinsic definitions are a bit out of my scope. Does that compile without issue, even if the VSCode extension complains?

**Comment by PolaricEntropy** [comment]
Yes it does, and the line doesn't get an error by the extension if I use the "native" keyword as a field modifier. I conferred with my local UE1 expert, hanfling, and he told me that "intrinsic" and "native" are mutually interchangeable in all places.
According to the [unreal wiki](https://wiki.beyondunreal.com/Classes#Native_implementation_modifiers) "intrinsic" is a valid keyword for UE1 and UE2, but that page might not be entirely accurate since it's gotten a few other things wrong. It might still be a good general guideline.

**Comment by EliotVU** [comment]
Sorry for the late response, and thanks for submitting this issue. 
It seems like I missed this keyword for variables! The fix should go live with version 0.5.

**Comment by PolaricEntropy** [comment]
Is v0.5 slated for release soon?

**Comment by EliotVU** [comment]
I plan to publish it in a moment, that is if the publishing features are still working on my end 📦
