### ISSUE TITLE
[0.5.0] Object literals use String/Name syntax highlighting

### ISSUE THREAD

**Issue by EpicYoshiMaster** [EliotVU/UnrealScript-Language-Service#136]
Before in [0.4.4]:
![image](https://user-images.githubusercontent.com/32598419/141022373-9347847f-46e7-4967-abfe-fb6aa517eb17.png)

Now in [0.5.0]:
![image](https://user-images.githubusercontent.com/32598419/141022590-d70f260b-1a43-4792-917e-19f2a3337d11.png)

(Awesome to see a new release by the way!)

**Comment by EliotVU** [comment]
Thanks! 

This was a change I had made a while ago, I believe the intention was to highlight it as a string as that is how the UnrealScript under the hood interprets it (e.g. it allows non-identifier characters too!). 

Nonetheless this issue will be resolved when SemanticTokens are supported. See issue #137
