### ISSUE TITLE
[0.5.0] (DefaultProperties) Issue with structs written on multiple lines

### ISSUE THREAD

**Issue by Un-Drew** [EliotVU/UnrealScript-Language-Service#138]
After writing a struct on multiple lines in DefaultProperties, everything else below it loses colors. It only happens on 0.5.0.
![image](https://user-images.githubusercontent.com/69184314/142730570-34a166e4-f124-4d36-b50e-45d8833b165c.png)

It doesn't happen when writing it on a single line without the curly brackets.
![image](https://user-images.githubusercontent.com/69184314/142730653-6e57527b-ed1e-4630-bbdb-0f0e8dfd91a6.png)

Seems like the closing bracket causes it, since removing it (aside from causing a syntax error) restores the colors:
![image](https://user-images.githubusercontent.com/69184314/142731033-233e90df-3643-4e16-af46-4f1bfc6bba7f.png)

**Comment by EliotVU** [comment]
Thanks!

I've got a fix ready for the next release.

![image](https://user-images.githubusercontent.com/808593/142751566-ba7f7b48-bfb8-419c-81bf-1c0165bc3760.png)
