### ISSUE TITLE
Intrinsic Vect function is not recognized as a valid function input.

### ISSUE THREAD

**Issue by Flameis** [EliotVU/UnrealScript-Language-Service#147]
**Describe the bug**
The intrinsic Vect function is not being recognized as a valid function input when put directly in the function params. 

**Screenshots**
![image](https://user-images.githubusercontent.com/40249557/207821574-9aaffd1f-2462-46fe-8766-b3c40fc38bcc.png)

**Comment by EliotVU** [comment]
Unfortunately the type-checking feature is stuck in the experimental stage, I recommend you to keep the "unrealscript.checkTypes" option disabled.

**Comment by Shtoyan** [comment]
> Unfortunately the type-checking feature is stuck in the experimental stage, I recommend you to keep the "unrealscript.checkTypes" option disabled.

Can you please add a text warning in settings? I've had several people asking me why it bugs for them.

![image](https://user-images.githubusercontent.com/22412356/210547792-837d8ec5-3e90-4f0e-be8e-dc84b0115e65.png)

**Comment by EliotVU** [comment]
@Shtoyan Done! And the typing issue had also been fixed with 0.6.0

**Comment by Shtoyan** [comment]
Thanks!
