### ISSUE TITLE
VSCode's Sticky scroll feature

### ISSUE THREAD

**Issue by Shtoyan** [EliotVU/UnrealScript-Language-Service#148]
**Describe the solution you'd like**

VSCode introduced [sticky scroll](https://code.visualstudio.com/updates/v1_71#_sticky-scroll) feature in V1.71.

![GIF](https://code.visualstudio.com/assets/updates/1_71/sticky-scroll-ctrlclick.gif)

It's a killer feature when you browse **huge** functions and especially with several classes opened at the same time.

Aaand it doesn't work your extension which is a unfortunate.

**Comment by Shtoyan** [comment]
> It also appears that all symbols are missing in the symbols list :( (i.e. Ctrl+R)

I was gonna make an other issue for that D: at least you know about it.

**Comment by EliotVU** [comment]
I updated the code to work the latest LSP specs. 

However VS Code still pretends to be not aware of any editor symbols, I've went through with it using the debugger, all the data it requires is there just fine, how strange...

I noticed that it is picking up the class definition symbol, despite not listing it under the editor symbols.

**Comment by EliotVU** [comment]
It works now! 

I figured it out by accident, when I noticed that some documents do show all symbols, but if there was even just one method with a return type it would all break. Apparently the generated "ReturnValue" parameter had a default range of zero, causing VSCode to error, a bit funny that a single symbol with an incorrect property just breaks it all.
