### ISSUE TITLE
Default UnrealScript snippets

### ISSUE THREAD

**Issue by Shtoyan** [EliotVU/UnrealScript-Language-Service#149]
**Describe the solution you'd like**

Is it technically possible to add some basic, default snippets here, without creating a standalone snippet extension? Something like these: https://github.com/InsultingPros/LazyKFWiki/blob/main/docs/_content/unrealscript.json

They are really helpful, not mandatory and if you add them, people will be able to easily modify them instead of writing from scratch.

**Comment by EliotVU** [comment]
That's a good idea. I will push some basic snippets shortly!

**Comment by EliotVU** [comment]
Ah, forgot to add structdefaultproperties and a snipper for interface :)

**Comment by EliotVU** [comment]
I think this issue can be closed, but I'll leave it open for review.

**Comment by Shtoyan** [comment]
Wow, that's much more that I was expecting.

From my little testing:

- There is no case for `local` variables.
- Maybe add `Role==ROLE_Authority` by default instead of `condition` string?
- There is a typo in replication block so it doesn't have a closing bracket.
![image](https://user-images.githubusercontent.com/22412356/211002343-902768bc-92ba-4468-adcc-fa669f4f226b.png)
- There is a whitelist instead of `;` for `new`.
- Maybe add `BeginState()` / `EndState()` for `state`?

**Comment by EliotVU** [comment]
Fixed :)

* As for role by default, this is an unnecessary condition if (bNetDirty or bNetInitial) is all that's needed, ROLE_Authority is always implied.
* Not sure, is this the very first thing to write when creating a state?
