### ISSUE TITLE
[Feature Request]: Pre-Release versions for VSCode Marketplace

### ISSUE THREAD

**Issue by Shtoyan** [EliotVU/UnrealScript-Language-Service#155]
### Is your feature request related to a problem? Please describe

Let's say I'm very happy with #148 fixed, and I can build from a fork for myself :d But lot's of people (at least some of my friends) will be lazy to set up a build system just to get the fixed-beta-minor version.

### Describe the solution you'd like

VSCode has a [pre-release](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions) feature, which allows to easily pick the latest, not tested version and check it. And it will allow more people to do it.

**Comment by EliotVU** [comment]
Gotcha, I'll give it a go :)

**Comment by Shtoyan** [comment]
Yusss, thanks for this feature!

**Comment by EliotVU** [comment]
> Yusss, thanks for this feature!

You're welcome!

Let me know if you ran into any regressions.
