### ISSUE TITLE
[Bug 0.6.3]: Class-function field hint

### ISSUE THREAD

**Issue by Shtoyan** [EliotVU/UnrealScript-Language-Service#161]
### Describe the bug

If one of your classes match the package name:

```text
TestPackage
|-- TestPackage.uc
|   ...
|-- class9.uc
|-- class10.uc
```

You won't be able to click-open-view the parent class, any of variables and functions - extension will show them as a current package.

### Screenshots

![image](https://user-images.githubusercontent.com/22412356/218086004-39695491-e9c4-4dd6-87e4-5373ada44dad.png)

![image](https://user-images.githubusercontent.com/22412356/218088476-a60ccf9f-0cd6-46dd-85ae-251dfe4e895c.png)

**Comment by Shtoyan** [comment]
Btw, latest version has some regressions. Do you want me to spam with issues or do I post them in gitter?

**Comment by EliotVU** [comment]
> Btw, latest version has some regressions. Do you want me to spam with issues or do I post them in gitter?

Sure, issues are preferred, they can be helpful later on to document changes. But if you got a question feel free to use gitter instead.
