### ISSUE TITLE
[Bug 0.6.3]: Type 'Font' not found

### ISSUE THREAD

**Issue by Shtoyan** [EliotVU/UnrealScript-Language-Service#163]
### Describe the bug

This should be added to native class list, yyeah?

P.S. checked on [kf1 sources](https://github.com/InsultingPros/KillingFloor).

**Comment by EliotVU** [comment]
UDK has a native class for this `Engine/Classes/Font.uc`, so I won't be adding this class to the list.

Ultimately, the idea is to either (or both) fetch this class from the compiled .u package (it's referenced in the import table), or look for an /inc/ folder and scan for the C++ declaration.
