### ISSUE TITLE
[Bug 0.6.3]: [Error - 9:40:23 PM] Request textDocument/documentSymbol failed.

### ISSUE THREAD

**Issue by randomperson189** [EliotVU/UnrealScript-Language-Service#169]
### Describe the bug

A bug happened!

Whenever I try and hover over any text, it always says Loading... and then this error shows up: [Error - 9:40:23 PM] Request textDocument/documentSymbol failed.

### Screenshots
![image](https://user-images.githubusercontent.com/32617562/219043911-c1e86da6-085d-4300-86e8-01a99fedd85c.png)

![image](https://user-images.githubusercontent.com/32617562/219043332-90392c6a-7c5a-4124-8079-bd0e1cd547ec.png)

**Comment by EliotVU** [comment]
My bad, an oversight I had made. You can work around this issue by adding the file to your current workspace.
