### ISSUE TITLE
Error highlighting is completely broken, please let me turn it off

### ISSUE THREAD

**Issue by TheMarkie** [EliotVU/UnrealScript-Language-Service#17]
Please give me the ability to turn off error highlighting. I'm using this extension on unrealscript 1 files and it completely breaks down. All comparison operators are "invalid". Most functions from external packages are considered to not exist.

This extension has most of the necessary highlighting to be fully functional (it still lacks proper highlighting for Class and Name type), however the error highlighting has never worked since the beginning and it can just go with no value loss. 

Context:
Extension settings: All 0.4.3 default settings with Unrealscript generation set to 1 (changing the generation DOES NOT fix this). 
Workspace: All folders for the package sources are included.
![error](https://user-images.githubusercontent.com/5463623/67632384-21c82c80-f8d5-11e9-956c-1a3ee9afc23f.png)

Please, this is a great extension and it helps a lot. It does not need error highlighting, and error highlighting is the only thing that's wrong with this extension, please turn it off.

**Comment by EliotVU** [comment]
By the looks of it, it appears that the extension can't find and index "Object.uc", are you sure that "Core/classes" are included in your workspace?

Nonethless, you can disable any errors under preferences -> UnrealScript -> Analyze Documents, 
e.g. http://prntscr.com/popa87
Change from All or OnlyActive to None.

p.s. Class highlighting is currently that way due limitations of the tmLanguage that VS Code uses to highlight code, other extensions may however workaround this with "hacks".

**Comment by TheMarkie** [comment]
Thanks for the fast response, but it didn't work at all, that's why I opened a problem.
![error](https://user-images.githubusercontent.com/5463623/68072565-cd7fe980-fdb9-11e9-83d6-cacd4e352e55.png)

**Comment by EliotVU** [comment]
Sorry for the late reply, but this will be fixed in the next update :)

**Comment by TheMarkie** [comment]
Thank you, the highlighter is pretty much perfect now. I gave it a 5-star review on the extension market.
