### ISSUE TITLE
[Bug]: Objects and Subobjects show errors in defaultproperties

### ISSUE THREAD

**Issue by randomperson189** [EliotVU/UnrealScript-Language-Service#170]
### Describe the bug

For some reason the formatting shows errors for Objects and Subobjects in defaultproperties even though they aren't errors and compile just fine

### Screenshots

![image](https://user-images.githubusercontent.com/32617562/219077317-e67f7f51-0826-45bf-a7ed-64369cc1b6b5.png)
![image](https://user-images.githubusercontent.com/32617562/219078713-d49a1f51-c42b-46bf-b8cd-9eefbd3a3b18.png)

**Comment by Un-Drew** [comment]
Just gonna to this: It only seems to happen when editing an already existing object. Defining new sub-objects by specifying the class works fine.

**Comment by EliotVU** [comment]
Yeah, the indexer fails to pickup the correct subobject from the inherited class. I haven't found the exact cause of this issue yet, it seems to work in certain circumstances, but as soon as the document is re-indexed it all breaks, likely an invalidation issue.
