### ISSUE TITLE
[Feature Request]: Publish to Open VSX

### ISSUE THREAD

**Issue by PhasecoreX** [EliotVU/UnrealScript-Language-Service#175]
### Is your feature request related to a problem? Please describe

I am not able to see and install this extension when searching for it in VSCodium.

### Describe the solution you'd like

Please publish this extension on https://open-vsx.org/, so that VSCodium (and other VS Code-like editors that use Open VSX) can see it and keep up to date.

### Describe alternatives you've considered

You can manually install it, but then you don't get automatic updates.

### Additional context

From their website:

What is Open VSX Registry?

The Open VSX Registry offers a community driven, fully open platform for publishing and consuming VS Code extensions. The Registry is built on Eclipse Open VSX, which is an open source project hosted at the Eclipse Foundation.

Open VSX is integrated into multiple software applications that support VS Code extensions. There is strong demand for a fully open alternative to the Visual Studio Marketplace, and with hundreds of great extensions already available, it is the intent of the Eclipse Foundation to enable continued and accelerated growth.

From me:

Thank you!

**Comment by EliotVU** [comment]
Done! https://open-vsx.org/extension/EliotVU/uc 

Thanks for informing me on this :)

**Comment by PhasecoreX** [comment]
You're welcome! Thanks for such a quick turnaround on this!
