### ISSUE TITLE
[Bug]: Missing highlighting in v0.6.5+

### ISSUE THREAD

**Issue by MQDuck** [EliotVU/UnrealScript-Language-Service#181]
### Describe the bug

For me, versions after 0.6.4 don't have highlighting for anything except parentheses, brackets and comments. The screenshot here is from v0.7.1.

### Screenshots

![highlighting](https://github.com/EliotVU/UnrealScript-Language-Service/assets/17994307/9eac774e-2986-4e32-9c08-bdf651977c59)

**Comment by MQDuck** [comment]
I should add that this is code for a Deus Ex mod. Perhaps it has something to do with the UnrealScript version.

**Comment by EliotVU** [comment]
Perhaps the macros may be the cause of this? like #var(prefix)
