### ISSUE TITLE
[Bug]: Declaring static array size from variable fails in some cases

### ISSUE THREAD

**Issue by tuokri** [EliotVU/UnrealScript-Language-Service#182]
### Describe the bug

Couple issues with static arrays:
- The extension does not understand `EnumType.EnumCount` syntax when declaring static array sizes.
- Certain static array size declarations that the extension understands report a false error if the array is a struct member.

### Screenshots

![image](https://github.com/EliotVU/UnrealScript-Language-Service/assets/16985292/1ab7c0ba-35d5-41f6-abce-eb9a230a3df6)

**Comment by EliotVU** [comment]
Thanks, will have to add these to current tests :)

see also:
https://github.com/EliotVU/UnrealScript-Language-Service/blob/22b6fbb79476f374c2d7b7c5884cacb7bc1e946c/server/src/UC/test/enum/EnumTest.uc
