### ISSUE TITLE
[Bug]: [v0.7.1] highlight source code as comment by mistake.

### ISSUE THREAD

**Issue by ballzb** [EliotVU/UnrealScript-Language-Service#183]
### Describe the bug

Hi there,

Please check the Screenshot.

### Screenshots

![image](https://github.com/EliotVU/UnrealScript-Language-Service/assets/35439854/c5624921-8a6d-4649-bbfb-50b541595109)

**Comment by EliotVU** [comment]
Wrong screenshot or wrong repository? The code in the screenshot is JavaScript.
