### ISSUE TITLE
[Suggestion] Chat platform

### ISSUE THREAD

**Issue by Xymanek** [EliotVU/UnrealScript-Language-Service#23]
Github issues are great for tracking and coordinating on long-term tasks but isn't really suitable for generic discussion. I suggest making a room on gitter.im so that we could discuss/coordinate(1) things easier

(1) For example, the question I would like to ask right now is "How far away is the next release? Should I make issues now or wait till next release (since I saw that there were a few commits already)"

**Comment by EliotVU** [comment]
Hey, I have followed your request and created a chat room at https://gitter.im/unrealscript.

To answer your question, I have not yet made any plans for a next release, as I haven't done much work on this project as of late, but I would appreciate it if you submit any issues.
