### ISSUE TITLE
[0.4.4] Closing unopened comment

### ISSUE THREAD

**Issue by Xymanek** [EliotVU/UnrealScript-Language-Service#28]
```uc
/**
 * Removes the values for all configurable properties in this object's class from the .ini file.
 *
 * @param	PropertyName		if specified, only this property's value will be removed.
 */
native static final function StaticClearConfig( optional string PropertyName );
*/
```
![image](https://user-images.githubusercontent.com/2865341/71414339-2c960800-265f-11ea-8968-53525e7e0af5.png)

The UC compiler obviously considers this fine, so perhaps downgrade it to a suggestion or something?

**Comment by midnight-dev** [comment]
Does it really not care about an orphan tag?  `*/`
Granted, most of my UnrealScript experience is from 2006, but I thought the compiler was very temperamental about expected and unexpected tokens. To me, it looks like a syntax error.

**Comment by Xymanek** [comment]
While I agree that it shouldn't be legal, it works and it's from `Src/Core/Classes/Object.uc`

**Comment by midnight-dev** [comment]
Yikes. Never noticed that. Which version of Unreal / Unreal Tournament / Unreal Engine is that in? And if this were to be rated as a warning instead of a syntax error, would it help developers? It could be a pain to check if the syntax highlighter should care about orphan tokens like this every time */ is found. I'll see if I can find this issue in UT2004 UScript.

**Comment by Xymanek** [comment]
XCOM2: WOTC. So UE3 + some Firaxis additions (but this isn't marked/commented as one of them)

**Comment by EliotVU** [comment]
UE2 throws this error: "Error, Unexpected '*/' outside of comment" I think the best choice is to leave this as an valid error (maybe a warning?).

**Comment by Xymanek** [comment]
So, I also got `Error, Unexpected '*/' outside of comment` when I tried to repro it. However, upon further digging, it appears that UCC supports "nested comments" (or something???) since the following perfectly compiles:

```uc
/*
/**
 * asdfg
 */
*/
```
