### ISSUE TITLE
[0.4.4] Default value isn't enough to consider argument optional

### ISSUE THREAD

**Issue by Xymanek** [EliotVU/UnrealScript-Language-Service#29]
```uc
native final function SetPos(float PosX, float PosY, float PosZ=0.0);
```
![image](https://user-images.githubusercontent.com/2865341/71414503-ef7e4580-265f-11ea-86d6-ada2849bb9e0.png)

```uc
Canvas.SetPos(4, out_YPos);
```
![image](https://user-images.githubusercontent.com/2865341/71414526-0a50ba00-2660-11ea-8bf2-4e03eec80751.png)

The UC compiler obviously considers this fine, so perhaps downgrade it to a suggestion or something?

**Comment by EliotVU** [comment]
Fixed by commit https://github.com/EliotVU/UnrealScript-Language-Service/commit/08f898e8448c110ac771ff78b43f7eb5c5efc0b7
