### ISSUE TITLE
[0.4.4] nameof isn't recognized as name for SetTimer

### ISSUE THREAD

**Issue by Xymanek** [EliotVU/UnrealScript-Language-Service#33]
![image](https://user-images.githubusercontent.com/2865341/71415515-c6ac7f00-2664-11ea-8c26-14d575e297f2.png)

**Comment by EliotVU** [comment]
Thanks, this is one of the many current issues when "check types" is enabled, a WIP feature.

**Comment by EliotVU** [comment]
Another issue in regards to "nameof" 
![image](https://user-images.githubusercontent.com/808593/71425775-2fb1e800-26a1-11ea-8ad7-fa86da6133f9.png)

I'll have to verify what the exact boundaries are of "nameof", does the compiler accept any static expression inside of this constant?
