### ISSUE TITLE
Make error squiggles optional

### ISSUE THREAD

**Issue by TheMarkie** [EliotVU/UnrealScript-Language-Service#8]
Right now everything works wonders except for the error squiggles. Since the Intellisense doesn't know how to deal with native functions/classes that don't have declarations in the immediate workspace, nearly every script has errors all over the place. Can we get an option to turn this off?

**Comment by EliotVU** [comment]
I'll implement this for the next release. Thanks for the feedback :)

p.s. I recommend adding the Core/Engine folders to your workspace.

**Comment by TheMarkie** [comment]
Well my workspace already has Core/Engine included but then that folder would also have error squiggles (things like extending Object which doesn't exist).

I really appreciate what you're doing here, and it's a lot for the UE1 modding community as a whole, thank you :)
